### ISSUE TITLE
splitting

### ISSUE THREAD

**Issue by joshuabest541** [danieladov/jellyfin-plugin-mergeversions#14]
Splitting is not working on 10.7 stable. It just says "An unexpected error has occurred".

**Comment by danieladov** [comment]
Could you post more logs? I just tried and it's working for me. 
Are you using the last version of the plugin?

**Comment by joshuabest541** [comment]
Hello, I checked after a day and the libraries had indeed split up, the error appears but doesn't appear to o effect anything. Thanks
