### ISSUE TITLE
Plugin Does Not Work With 10.8.0

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [danieladov/jellyfin-plugin-mergeversions#22]
Running version 10.8.0.0 of the plugin with version 10.8.0 Jellyfin. The plugin's status is "Not Supported"

**Comment by inzi2u** [comment]
i have noticed this too..

**Comment by Cookie-Monster-Coder** [comment]
Yeah, I think all his plugins are dead/abandoned.

**Comment by danieladov** [comment]
It's not abandoned😉. I'm working already on it, I should have a new version for my plugin in the next few days.

**Comment by danieladov** [comment]
I've just released a new version for 10.8.0

**Comment by inzi2u** [comment]
thank you danieladov, i've just installed it, will report back on how
things go..
you're the best!!!
