### ISSUE TITLE
Request: Instead of displaying the full file name is it possible to only use Quality, Edition, Audio, etc 

### ISSUE THREAD

**Issue by db-alakaboom** [danieladov/jellyfin-plugin-mergeversions#34]
I want users to be able to toggle between "4K" and "1080p" etc. rather than guessing based on the cutoff name of the video which happens occasionally due to this recommend naming scheme.

 {Movie CleanTitle} {(Release Year)} [imdbid-{ImdbId}] - {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]{MediaInfo AudioLanguages}[{MediaInfo VideoBitDepth}bit][{Mediainfo VideoCodec}]{-Release Group} 

I'm not sure if possible but it would be a massive QoL improvement and less questions asked haha.

**Comment by danieladov** [comment]
Hi, this plugin only merges the movies, you should request it at [https://features.jellyfin.org/](https://features.jellyfin.org/)
