### ISSUE TITLE
how its work?

### ISSUE THREAD

**Issue by Sirfrancis18** [danieladov/jellyfin-plugin-mergeversions#4]
Hello
how does it work? because I have installed it through repository, I have restarted, I have updated library, I have updated metadata and it does not work
manually yes that works

**Comment by danieladov** [comment]
Hi, you can go to Schedule task and press the "play" button of Merge Movies or Merge Episodes

![Anotación 2020-09-01 164358](https://user-images.githubusercontent.com/29411250/91866139-76b19d80-ec72-11ea-83bb-5f90d60d70ef.png)

**Comment by Sirfrancis18** [comment]
that doesn't appear to me

**Comment by danieladov** [comment]
Are you using windows?
Try to uninstall the plugin and install again through repository
