### ISSUE TITLE
Show only the version in the dropdown

### ISSUE THREAD

**Issue by Nodiink** [danieladov/jellyfin-plugin-mergeversions#42]
When Jellyfin merges using the naming convention, the dropdown to select the video source only shows the version name. With this plugin, the full movie/episode title is shown. Is it possible to create a parameter so that the text of the film/episode shows only the "different" final piece?

**Comment by danieladov** [comment]
Hi, this plugin is only responsible for merging the movies. Jellyfin decides how to display them on the web, so you should inquire on Jellyfin's GitHub page
