### ISSUE TITLE
Jellyfin unstable 10.9 support - Status Malfunctioned

### ISSUE THREAD

**Issue by Cebrain** [danieladov/jellyfin-plugin-mergeversions#43]
Hi,

i upgraded to the latest stable and saw that the merge versions plugin is working for my movies but still when i check the plugin page i see the Status Malfunctioned.

Sadly i have no idea how to provide a useful log, because at the start the log is already filled with massive entrys.
To replicate, you only would need a fresh instance with the plugin activated

![image](https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/78339531/e28274fb-49bd-4546-b921-1f4dc18e6425)

**Comment by danieladov** [comment]
Hi, I will update the plugin once the first beta version is released.
