### ISSUE TITLE
Suggestion regarding TV merge

### ISSUE THREAD

**Issue by Ezzahhh** [danieladov/jellyfin-plugin-mergeversions#5]
Hi,

Great plugin! This isn't really an issue, but I was wondering if it was possible to merge TV episodes together since it will already do series. By this I mean, I might have two episodes that are the same in different qualities and Jellyfin will just display them one after the other and becomes quite annoying to watch if a show with 25 episodes has 50 because of different versions. Would there be any way to merge them? I believe it would need to use TVDB episode id or imdb id.

Also, do you think it would be possible for merging to be done on not just Tmdb?

Thanks!

**Comment by danieladov** [comment]
The plugin should be already doing this

**Comment by Ezzahhh** [comment]
Yes that was my bad, I will test fully when my library scan is complete. Thank you!
