### ISSUE TITLE
[Feature Request] Plex versions support

### ISSUE THREAD

**Issue by major-sam** [danieladov/jellyfin-plugin-mergeversions#64]
Is it possible to include plex optimized version to watch with this plugin?

possible solution/workarounds:

1. Separated library  folder for plex optimisations:
    add `/my_media/Plex Versions/My Quality[720,1080,.....]/` as libraries in jellyfin
2. link all files in `Plex Versions` to root item folder `ln './Plex Versions/{quality detection?}/{item name} ./{item name} - {quality}`

Both solutions has disadvantages:
1. To much folders with custom quality in plex
2. To much files in item folder - scanner can go crazy on plex or jellyfin

**Comment by danieladov** [comment]
Hi, I don't think there's much I can do. The plugin needs the movies to be scanned by Jellyfin in order to merge them.
